// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kvimldbhqcymkvmzjovx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2aW1sZGJocWN5bWt2bXpqb3Z4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMTMwMTMsImV4cCI6MjA2Mzc4OTAxM30.CWyUi6Y_m81mVCn09LEmq8XR41_LhzzmE5Sh0Qh-e7I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);